### PR TITLE
Allow users to repeat a trip

### PR DESCRIPTION
**Pull request by iamthuypham**
# Description

New trips route `/repeat`

Repeat flow:
- Copy original trip and create new trip with empty waypoints
- Copy original trip's waypoints to new repeated trip

All dates in repeated trip are added up based of different time (in miliseconds)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbotello** [comment]
Do we really need an extra endpoint to add this functionality? On the server-side, all we would need to do is reset the datetime of `Trip` and all `Waypoints`. That can be handled easily with our existing `PUT` endpoints. It looks like you're creating a whole new `Trip` with a `POST` and I don't think its a good idea to essentially add duplicate trips to the db when the only things changed are the dates and `REPEAT` is being added to the Trip name

**Comment by iamthuypham** [comment]
@alexbotello I think this is an ambiguous part. Needs more clarification. cc @frankfaustino 

From the mockup: 
"Repeats open new trip window with **a copy of the previous trip**, but date and time fields are empty"

**Comment by frankfaustino** [comment]
I imagine a user would want a history of past trips in their archives. Re-using an existing trip for repeat and overwriting its start/end times and trip data wouldn't allow for that. Also, we could potentially spin-off some useful features given enough data points from a user's trip history. Just some food for thought.

**Comment by alexbotello** [comment]
That’s a good point about collecting data for previous trips. Okay, I’m on board. 

But I do think we should nix `REPEAT` being added to the trip name. It should stay the same unless a user chooses to change it. The previous trip will be archived anyways

**Comment by iamthuypham** [comment]
The repeat button only appears in /archive path

**Pull request merged**
